---
title: "git_01"
author: "Chris Gonzalez"
date: "Summer 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

In the depths of my heart, a story unfolds,   
Of a love that's eternal, a tale yet untold.   
Marianna, my wife, a beacon so bright,   
With eyes that reflect a celestial light.   

Two sons we cherish, our blessings, our pride,   
Anakin, a spirit with dreams that collide,   
Andres, so tender, a soul full of grace,   
Together we weave a harmonious embrace.   

From the first light of dawn to the last star's gleam,   
We'll journey as one, fulfilling our dream.   
Through laughter and tears, joys and sorrows,   
We'll hold each other, today and tomorrows.   

Hand in hand, we'll wander life's winding road,   
Through fields of love and stories yet untold.   
Like a symphony's melody, our hearts intertwine,   
A love so profound, an infinite sign.   

In your embrace, time stands still,   
As we build memories that forever will fill,   
Our souls with a warmth that cannot decay,   
A love that strengthens with each passing day.   

Anakin, a beam of hope, shining so bright,   
Andres, a gentle star, lighting up the night.   
In their innocent eyes, our love they perceive,   
A legacy of love that they'll always believe.   


